---
minimum_pre_commit_version: 2.10.1
# default_language_version:
#   python: python3.9
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  # pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # Prevent giant files from being committed.
      - id: check-added-large-files
      # Simply check whether files parse as valid python.
      - id: check-ast
      # Require literal syntax when initializing empty or zero Python builtin
      # types.
      - id: check-builtin-literals
      # Forbid files which have a UTF-8 byte-order marker
      - id: check-byte-order-marker
      # Check for files with names that would conflict on a case-insensitive
      # filesystem like MacOS HFS+ or Windows FAT.
      - id: check-case-conflict
      # Checks for a common error of placing code before the docstring.
      - id: check-docstring-first
      # check-executables-have-shebangs
      #- id: check-executables-have-shebangs
      # Attempts to load all json files to verify syntax.
      # - id: check-json
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything.
      # - id: check-symlinks
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Ensures that links to vcs websites are permalinks.
      - id: check-vcs-permalinks
      # Attempts to load all xml files to verify syntax.
      # - id: check-xml
      # Attempts to load all yaml files to verify syntax.
      - id: check-yaml
      # Check for debugger imports and breakpoint() calls in python source.
      - id: debug-statements
      # Detects symlinks which are changed to regular files with a content
      - id: destroyed-symlinks
      # Checks for the existence of AWS secrets, set up with the AWS CLI.
      # - id: detect-aws-credentials
      # Checks for the existence of private keys.
      - id: detect-private-key
      # This hook replaces double quoted strings with single quoted strings.
      # - id: double-quote-string-fixer (KEEP DISABLED)
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
      # Removes "# -*- coding: utf-8 -*-" on the top of python files.
      - id: fix-encoding-pragma
        args: [ "--remove" ]
      # Sort the lines in specified files (defaults to alphabetical).
      # - id: file-contents-sorter (KEEP DISABLED)
      # Replaces or checks mixed line ending to LF.
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      # Assert that files in tests/ match test*.py.
      - id: name-tests-test
        args: [ "--django" ]
      # Protect specific branches from direct checkins.
      - id: no-commit-to-branch
        args:
          - "-b master"
          - "-p release/.*"
      # Checks that all your JSON files are pretty.
      # - id: pretty-format-json
      #   args: ["--autofix"]
      # Sorts entries in requirements.txt and removes incorrect entry
      # - id: requirements-txt-fixer  (KEEP DISABLED)
      # Sorts simple YAML files which consist only of top-level keys,
      # preserving comments and blocks.
      # - id: sort-simple-yaml  (KEEP DISABLED)
      # Trims trailing whitespace.
      - id: trailing-whitespace
      # - id: flake8
      #   additional_dependencies: ["flake8-bugbear"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.1
    hooks:
      # Enforce that noqa annotations always occur with specific codes.
      # Sample annotations: # noqa: F401, # noqa: F401,W203
      - id: python-check-blanket-noqa
      # Prevent common mistakes of assert mck.not_called(),
      # assert mck.called_once_with(...) and mck.assert_called.
      - id: python-check-mock-methods
      # A quick check for the eval() built-in function
      - id: python-no-eval
      # A quick check for the deprecated .warn() method of python loggers
      - id: python-no-log-warn
      # Enforce that python3.6+ type annotations are used instead of
      # type comments
      - id: python-use-type-annotations
      # Detect common mistake of using single backticks when writing rst
      - id: rst-backticks
      # Detect mistake of rst directive not ending with double colon
      - id: rst-directive-colons
      #Detect mistake of inline code touching normal text in rst
      - id: rst-inline-touching-normal
      # Forbid files which have a UTF-8 Unicode replacement character
      - id: text-unicode-replacement-char

  # isort
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        additional_dependencies: [ toml ]

  # format: black
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black

  # flake8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [ "flake8-bugbear" ]

  # check docstrings
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
        args: [ "--ignore=D10,D21,D202" ]

  # static type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy

  # vulture
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.3"
    hooks:
      - id: vulture
