---
# https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    # - asdf plugin add uv
    - asdf plugin add rye
    # - asdf install uv latest
    - asdf install rye latest
    # - asdf global uv latest
    - asdf global rye latest
    # - uv venv
    # - uv pip install .[docs]
    - rye sync --all-features
    - .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html
