# matrixctl
# Copyright (c) 2020  Michael Sasser <Michael@MichaelSasser.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
name: Python CI

on:
  push:
    branches: ["main"]
    paths-ignore: ["*.md"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"

      - name: Setup Rye
        id: setup-rye
        uses: eifinger/setup-rye@v4
        with:
          version: "0.41.0"
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Project Dependencies
        run: rye sync --all-features --no-lock

      - name: Run pre-commit
        run: |
          . .venv/bin/activate
          pre-commit run --all-files

      - name: Sphinx Build
        working-directory: ./docs
        run: |
          . ../.venv/bin/activate
          make html

      - name: Test with pytest
        run: |
          . .venv/bin/activate
          rye test
