---
name: github pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      working-directory: ./docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: |
          echo '::group::UV Version'
          uv --version
          echo '::endgroup::'

          echo '::group::Install Python'
          uv python install 3.13
          echo '::endgroup::'

          echo '::group::Install Dependencies'
          uv sync --all-extras --dev
          echo '::endgroup::'

      - name: Make docs
        working-directory: ${{env.working-directory}}
        run: uv run make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
